apiVersion: v1
kind: Service
metadata:
  name: ms-application-service
  namespace: dev-gke1
  labels:
    app: ms-app
spec:
  ports:
    - port: 1680
  selector:
    app: ci-deploy
    tier: backend
  type: LoadBalancer
